# Generated by Django 3.2.9 on 2021-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField(max_length=200)),
                ('msg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
